### ISSUE TITLE
Change Locale error

### ISSUE THREAD

**Issue by tamdragle** [algolia/voice-overlay-ios#12]
When I change change locale like so:
```
var voiceOverlayController: VoiceOverlayController {
    let recordableHandler = {
        return SpeechController(locale: Locale(identifier: "en_US"))
    }
    return VoiceOverlayController(speechControllerHandler: recordableHandler)
 }
``` 
 I get a crash when run:
```
inputViewController.dismissHandler = { [unowned self] (retry) in
          self.inputViewController = nil
          if retry {
            self.showRecordingScreen(view)
          }
        }

```
>Fatal error: Attempted to read an unowned reference but the object was already deallocated2019-01->10 10:09:32.479917+0700 hoaanhdao[2018:372531] Fatal error: Attempted to read an unowned >reference but the object was already deallocated
>(lldb)

**Comment by spinach** [comment]
Hi @tamdragle - I think this is probably related to this issue here https://github.com/algolia/voice-overlay-ios/issues/4#issuecomment-430298541. Basically you're losing reference to the voice controller. You need to keep a strong reference to it. 

Feel free to re-open the issue if it doesn't solve your issue

**Comment by tamdragle** [comment]
Hi @spinach Thank you!
